'use client';

import { Dispatch, SetStateAction, useState } from 'react';
import { ProposalConfig, NicheKey } from '@/app/proposta-comercial/config/types';

export function AdminPanel({ open, onClose, config, setConfig, onReset, onExport }: { open:boolean; onClose:()=>void; config:ProposalConfig; setConfig:Dispatch<SetStateAction<ProposalConfig>>; onReset:()=>void; onExport:()=>void }) {
  const [tab,setTab]=useState<'client'|'proposal'|'metrics'|'simulator'|'content'|'plans'|'visual'>('client');
  if(!open) return null;
  const update=(group:keyof ProposalConfig,key:string,value:any)=>setConfig(prev=>({...prev,[group]:{...(prev[group] as any),[key]:value}}));
  const niche=config.niches[config.client.niche];
  const updateNicheField=(key:string,value:any)=>setConfig(prev=>({
    ...prev,
    niches:{...prev.niches,[prev.client.niche]:{...prev.niches[prev.client.niche],[key]:value}}
  }));
  const updatePlan=(index:number,key:string,value:any)=>setConfig(prev=>({
    ...prev, plans: prev.plans.map((plan,i)=>i===index?{...plan,[key]:value}:plan)
  }));
  return <div className="admin-backdrop" onMouseDown={onClose}><aside className="admin-panel" onMouseDown={e=>e.stopPropagation()}><div className="admin-head"><div><span>MODO ADMIN</span><strong>Editar proposta</strong></div><button onClick={onClose}>×</button></div><div className="admin-tabs">{[['client','Cliente'],['proposal','Proposta'],['metrics','Métricas'],['simulator','Simulador'],['content','Conteúdo'],['plans','Planos'],['visual','Visual']].map(([k,l])=><button key={k} onClick={()=>setTab(k as any)} className={tab===k?'active':''}>{l}</button>)}</div><div className="admin-body">
    {tab==='client'&&<><Field label="Nome" value={config.client.name} onChange={v=>update('client','name',v)}/><Field label="Empresa" value={config.client.company} onChange={v=>update('client','company',v)}/><label className="admin-field"><span>Nicho</span><select value={config.client.niche} onChange={e=>update('client','niche',e.target.value as NicheKey)}>{(Object.entries(config.niches) as [NicheKey,typeof niche][]).map(([k,n])=><option value={k} key={k}>{n.label}</option>)}</select></label><Field label="Cidade" value={config.client.city} onChange={v=>update('client','city',v)}/><Field label="Logo (URL opcional)" value={config.client.logo||''} onChange={v=>update('client','logo',v)}/><Field label="Responsável" value={config.client.responsible} onChange={v=>update('client','responsible',v)}/><Field label="Data" value={config.client.date} onChange={v=>update('client','date',v)}/></>}
    {tab==='proposal'&&<><Num label="Valor da gestão" value={config.proposal.managementFee} onChange={v=>update('proposal','managementFee',v)}/><Num label="Investimento recomendado" value={config.proposal.recommendedAdSpend} onChange={v=>update('proposal','recommendedAdSpend',v)}/><Field label="Prazo" value={config.proposal.deadline} onChange={v=>update('proposal','deadline',v)}/><Field label="Condições" value={config.proposal.conditions} onChange={v=>update('proposal','conditions',v)} area/><Num label="Desconto (%)" value={config.proposal.discount} onChange={v=>update('proposal','discount',v)}/><Field label="Validade" value={config.proposal.validity} onChange={v=>update('proposal','validity',v)}/><Field label="Serviços inclusos (um por linha)" value={config.proposal.servicesIncluded.join('\n')} onChange={v=>update('proposal','servicesIncluded',v.split('\n').filter(Boolean))} area/><Field label="Link — Quero começar" value={config.cta.start} onChange={v=>update('cta','start',v)}/><Field label="Link — Tenho uma dúvida" value={config.cta.question} onChange={v=>update('cta','question',v)}/><Field label="Link — Aprovar proposta" value={config.cta.approve} onChange={v=>update('cta','approve',v)}/></>}
    {tab==='metrics'&&<>{Object.entries(config.metrics).map(([k,v])=><Num key={k} label={humanize(k)} value={v} onChange={n=>update('metrics',k,n)}/>)}</>}
    {tab==='simulator'&&<>{Object.entries(config.calculator).map(([k,v])=><Num key={k} label={humanize(k)} value={v} onChange={n=>update('calculator',k,n)}/>)}</>}
    {tab==='content'&&<><Field label="Nome do nicho" value={niche.label} onChange={v=>updateNicheField('label',v)}/><Field label="Headline do nicho" value={niche.headline} onChange={v=>updateNicheField('headline',v)} area/><Field label="Problema" value={niche.problem} onChange={v=>updateNicheField('problem',v)} area/><Field label="Argumento" value={niche.argument} onChange={v=>updateNicheField('argument',v)} area/><Field label="Exemplo de anúncio" value={niche.adExample} onChange={v=>updateNicheField('adExample',v)} area/><Field label="Headline da landing page" value={niche.landingHeadline} onChange={v=>updateNicheField('landingHeadline',v)} area/><Field label="Subheadline da landing page" value={niche.landingSubheadline} onChange={v=>updateNicheField('landingSubheadline',v)} area/><Field label="Estratégias (uma por linha)" value={niche.strategy.join('\n')} onChange={v=>updateNicheField('strategy',v.split('\n').filter(Boolean))} area/><Field label="Conversões (uma por linha)" value={niche.conversionTypes.join('\n')} onChange={v=>updateNicheField('conversionTypes',v.split('\n').filter(Boolean))} area/></>}
    {tab==='plans'&&<>{config.plans.map((plan,i)=><div className="admin-plan" key={i}><strong>Plano {i+1}</strong><Field label="Nome" value={plan.name} onChange={v=>updatePlan(i,'name',v)}/><Num label="Valor mensal" value={plan.price} onChange={v=>updatePlan(i,'price',v)}/><Field label="Descrição" value={plan.description} onChange={v=>updatePlan(i,'description',v)} area/><Field label="Itens (um por linha)" value={plan.items.join('\n')} onChange={v=>updatePlan(i,'items',v.split('\n').filter(Boolean))} area/><Field label="Badge" value={plan.badge||''} onChange={v=>updatePlan(i,'badge',v)}/><label className="admin-check"><input type="checkbox" checked={!!plan.featured} onChange={e=>updatePlan(i,'featured',e.target.checked)}/><span>Destacar como recomendado</span></label><Field label="CTA" value={plan.cta} onChange={v=>updatePlan(i,'cta',v)}/></div>)}</>}
    {tab==='visual'&&<><Field label="Nome da marca" value={config.brand.name} onChange={v=>update('brand','name',v)}/><Field label="Descrição" value={config.brand.descriptor} onChange={v=>update('brand','descriptor',v)}/><label className="admin-field"><span>Cor principal</span><input type="color" value={config.brand.primary} onChange={e=>update('brand','primary',e.target.value)}/></label><label className="admin-field"><span>Cor de destaque</span><input type="color" value={config.brand.accent} onChange={e=>update('brand','accent',e.target.value)}/></label></>}
  </div><div className="admin-footer"><button onClick={onExport}>Exportar JSON</button><button onClick={onReset} className="danger">Restaurar padrão</button></div></aside></div>
}
function humanize(s:string){return s.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase())}
function Field({label,value,onChange,area}:{label:string;value:string;onChange:(v:string)=>void;area?:boolean}){return <label className="admin-field"><span>{label}</span>{area?<textarea value={value} onChange={e=>onChange(e.target.value)}/>:<input value={value} onChange={e=>onChange(e.target.value)}/>}</label>}
function Num({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}){return <label className="admin-field"><span>{label}</span><input type="number" value={value} onChange={e=>onChange(Number(e.target.value)||0)}/></label>}
